---
- hosts: all
  vars:
    packages: ["postgresql", "postgresql-contrib"]
  tasks:
   - name: Install packages
     become: true
     become_method: sudo
     apt: 
      name: "{{ packages }}"
      state: present

   - name: Acces to postgresql
     become: true
     become_method: sudo
     command: sudo -u postgres psql -c 'CREATE TABLE IF NOT EXISTS series ( id int, nombre varchar(50));'

   - name: Alter user
     become: true
     become_method: sudo
     command: sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'psswrd';"

   - name: Allow connections
     become: true
     become_method: sudo
     command: sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/10/main/postgresql.conf

   - name: Allow connections
     become: true
     become_method: sudo
     command: sed -i "s/127.0.0.1\/32/0.0.0.0\/0/" /etc/postgresql/10/main/pg_hba.conf

   - name: Restart service
     become: true
     become_method: sudo
     command: sudo service postgresql restart


